on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ssvpdigitalAPI    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.14'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Clean up node_modules and package-lock.json
        run: |
          rm -rf frontend/node_modules
          rm -f frontend/package-lock.json

      # Instalar dependências do frontend
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Build do frontend
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Instalar dependências do backend
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Empacotar o build como um artefato
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ssvp  # Nome do artefato a ser criado
          path: |
            frontend/dist/**    # Inclui todos os arquivos do build do frontend
            backend/**           # Inclui todos os arquivos do backend

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ssvp

      - name: 'Deploy to Azure WebApp'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './ssvp'  # Diretório temporário onde o artefato foi baixado

